flowchart LR
  cmd_queue>Command queue]
  loop((Write loop))
  cmd_queue --> loop((Write loop))

  subgraph Connections
    conn1[/Connection 1 - busy/]:::busy
    conn2[/Connection 2 - busy/]:::busy
    conn3[/Connection 3 - busy/]:::busy
    conn4[/Connection 4 - busy/]:::busy
    classDef busy fill: red;
  end

  loop --> conn1
  loop -.-> conn2
  loop -.-> conn3
  loop -.-> conn4
